### ISSUE TITLE
Thanks for doing this

### ISSUE THREAD

**Issue by OlliV** [Qix-/handler-agent#1]
This is exactly what I needed some time ago but couldn't immediately figure out anything even decently well working, and thus decided to maybe check it later. So far this seems to work for our use case here https://github.com/turist-cloud/micri/pull/25 😍 

Thanks!

**Comment by Qix-** [comment]
Aw @OlliV this made my day - very good to hear from you <3 :) glad it works for you! Let me know if you encounter any issues and I'll fix them asap ^^

Hope all is well and you're staying safe!!
